services:
  server1:
    container_name: server1
    build: ./server1
    ports:
      - "8199:3000"
    command: "node server.mjs"
  server2:
    container_name: server2
    build: ./server2
    command: "python server.py"
